#
# Copyright (c) 2019-2024 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

name: Build

on:
  push:
    branches: [develop, master]
    tags: ['*']
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y --no-install-recommends \
                ca-certificates \
                clang-19 \
                llvm-19 \
                libclang-rt-19-dev \
                libc++-19-dev \
                libc++abi-19-dev \
                git \
                ninja-build \
                cmake \
                python3 \
                python-is-python3
      - run: python tools/ci.py
