#
# Copyright (c) 2024 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

name: Build

on:
  push:
    branches: [develop, master]
    tags: ['*']
  pull_request:
  workflow_dispatch:


jobs:
  clang-19:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4
      - run: bash tools/ubuntu-install.sh
      - run: python tools/ci.py --toolset=clang
  msvc:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: choco install ninja
      - shell: cmd
        run: | 
          "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat" x64 && python tools/ci.py --toolset=msvc
